/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visao.EstadoCivil;

import com.mycompany.dao.DaoEstadoCivil;
import com.mycompany.ferramentas.Constantes;
import com.mycompany.ferramentas.DadosTemporarios;
import com.mycompany.ferramentas.Formularios;
import com.mycompany.modelo.ModEstadoCivil;
import javax.swing.JOptionPane;

/**
 *
 * @author batista.4995
 */
public class CadEstadoCivil extends javax.swing.JFrame {

    /**
     * Creates new form CadEstadoCivil
     */
    public CadEstadoCivil() {
        initComponents();
        if(!existeDadosTemporarios()){
                   DaoEstadoCivil daoEstadoCivil = new DaoEstadoCivil();

                   int id = daoEstadoCivil.buscarProximoId(); 
                   if (id >= 0)
                       tfId.setText(String.valueOf(id));

                   btnAcao.setText(Constantes.BTN_SALVAR_TEXT);
                   btnExcluir.setVisible(false);
               }else{
                   btnAcao.setText(Constantes.BTN_ALTERAR_TEXT);
                   btnExcluir.setVisible(true);
               }

               setLocationRelativeTo(null);

               tfId.setEnabled(false);

        }
            private Boolean existeDadosTemporarios(){        
            if(DadosTemporarios.tempObject instanceof ModEstadoCivil){
                int id = ((ModEstadoCivil) DadosTemporarios.tempObject).getId();
                String nome = ((ModEstadoCivil) DadosTemporarios.tempObject).getNome();

                tfId.setText(String.valueOf(id));
                tfEstadoCivil.setText(nome);

                DadosTemporarios.tempObject = null;

                return true;
            }else
                return false;
        }
            private void inserir(){
            DaoEstadoCivil daoEstadoCivil = new DaoEstadoCivil();

            if (daoEstadoCivil.inserir(Integer.parseInt(tfId.getText()), tfEstadoCivil.getText())){
                JOptionPane.showMessageDialog(null, "Estado Civil salvo com sucesso!");

                tfId.setText(String.valueOf(daoEstadoCivil.buscarProximoId()));
                tfEstadoCivil.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possível salvar o Estado Civil!");
            }
        }
            private void alterar(){
            DaoEstadoCivil daoEstadoCivil = new DaoEstadoCivil();

            if (daoEstadoCivil.alterar(Integer.parseInt(tfId.getText()), tfEstadoCivil.getText())){
                JOptionPane.showMessageDialog(null, "Estado Civil alterado com sucesso!");

                tfId.setText("");
                tfEstadoCivil.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possível alterar o Estado Civil!");
            }

            ((ListEstadoCivil) Formularios.listEstadoCivil).listarTodos();

            dispose();
        }
            private void excluir(){
            DaoEstadoCivil daoEstadoCivil = new DaoEstadoCivil();

            if (daoEstadoCivil.excluir(Integer.parseInt(tfId.getText()))){
                JOptionPane.showMessageDialog(null, "EstadoCivil " + tfEstadoCivil.getText() + " excluída com sucesso!");

                tfId.setText("");
                tfEstadoCivil.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possível excluir o Estado Civil!");
            }

            ((ListEstadoCivil) Formularios.listEstadoCivil).listarTodos();

            dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAcao = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        tfId = new javax.swing.JTextField();
        tfEstadoCivil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Categoria");

        btnAcao.setText("Salvar");
        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAcao)
                        .addGap(27, 27, 27)
                        .addComponent(btnExcluir))
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcao)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void btnAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoActionPerformed
        DaoEstadoCivil daoEstadoCivil = new DaoEstadoCivil();
        
        if (btnAcao.getText() == Constantes.BTN_SALVAR_TEXT){
            inserir();
            
            tfId.setText(String.valueOf(daoEstadoCivil.buscarProximoId()));
            tfEstadoCivil.setText("");
            
        }
        else if (btnAcao.getText() == Constantes.BTN_ALTERAR_TEXT){
            alterar();
//            ((ListCategoria) Formularios.listCategoria).listarTodos();
            dispose();
        }
    
    }//GEN-LAST:event_btnAcaoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int escolha = 
                JOptionPane.showConfirmDialog(
                        null, 
                        "Deseja realmente excluir o estado civil " + tfEstadoCivil.getText() + "?");
        
        if(escolha == JOptionPane.YES_OPTION)
            excluir();
    }//GEN-LAST:event_btnExcluirActionPerformed
    private void formWindowClosed(java.awt.event.WindowEvent evt) {                                  
        Formularios.cadEstadoCivil = null;
    }                                 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadEstadoCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadEstadoCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadEstadoCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadEstadoCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadEstadoCivil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcao;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfEstadoCivil;
    private javax.swing.JTextField tfId;
    // End of variables declaration//GEN-END:variables
}
